# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=255, verbose_name='imi\u0119')),
                ('age', models.IntegerField(default=0, verbose_name='wiek (w miesi\u0105cach)')),
                ('birght_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=b'', verbose_name='obrazek')),
                ('agility', models.FloatField(default=0, verbose_name='zwinno\u015b\u0107')),
                ('obedience', models.FloatField(default=0, verbose_name='pos\u0142usze\u0144stwo')),
                ('stamina', models.FloatField(default=0, verbose_name='wytrzyma\u0142o\u015b\u0107')),
                ('strength', models.FloatField(default=0, verbose_name='si\u0142a')),
                ('speed', models.FloatField(default=0, verbose_name='szybko\u015b\u0107')),
                ('dressage', models.FloatField(default=0, verbose_name='uje\u017cd\u017canie')),
                ('trot', models.FloatField(default=0, verbose_name='k\u0142us')),
                ('gallop', models.FloatField(default=0, verbose_name='galop')),
                ('canter', models.FloatField(default=0, verbose_name='cwa\u0142')),
                ('jumping', models.FloatField(default=0, verbose_name='skoki')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=255, verbose_name='imi\u0119')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=b'', verbose_name='obrazek')),
                ('agility', models.FloatField(default=0, verbose_name='zwinno\u015b\u0107')),
                ('max_agility', models.FloatField(default=0, verbose_name='maksymalna zwinno\u015b\u0107')),
                ('obedience', models.FloatField(default=0, verbose_name='pos\u0142usze\u0144stwo')),
                ('max_obedience', models.FloatField(default=0, verbose_name='maksymalne pos\u0142usze\u0144stwo')),
                ('stamina', models.FloatField(default=0, verbose_name='wytrzyma\u0142o\u015b\u0107')),
                ('max_stamina', models.FloatField(default=0, verbose_name='maksymalna wytrzyma\u0142o\u015b\u0107')),
                ('strength', models.FloatField(default=0, verbose_name='si\u0142a')),
                ('max_strength', models.FloatField(default=0, verbose_name='maksymalna si\u0142a')),
                ('speed', models.FloatField(default=0, verbose_name='szybko\u015b\u0107')),
                ('max_speed', models.FloatField(default=0, verbose_name='maksymalna szybko\u015b\u0107')),
            ],
        ),
        migrations.AddField(
            model_name='horse',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horse.Race', verbose_name='rasa'),
        ),
    ]
