# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('money', models.IntegerField(default=2000, verbose_name='pieni\u0105dze')),
                ('friends', models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='znajomi')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='u\u017cytkownik')),
            ],
        ),
    ]
